version: '2'
services:
  postgres:
    image: "postgres:alpine"
    container_name: tgic-postgres-devnet
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    networks:
      - core
    environment:
     POSTGRES_PASSWORD: password
     POSTGRES_DB: tgic_core_devnet
     POSTGRES_USER: tgic

  core:
    build: 
      context: .
      dockerfile: Dockerfile
    image: tgic-core
    container_name: tgic-core-devnet
    restart: always
    ports:
     - "4102:4102"
     - "4103:4103"
     - "127.0.0.1:4004:4004"
     - "127.0.0.1:4005:4005"
     - "127.0.0.1:8080:8080"
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_TIME
    volumes:
     -  core:/home/tgic/core-bridgechain
    networks:
      - core
    env_file: ./devnet.env
    tty: true
    links:
     - postgres
    depends_on:
      - postgres
volumes:
  postgres:
  core:
networks:
  core:                                                          
